version: '3.1'
services:
  ewm-service:
    build: ewm-main
    container_name: ewm-main
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_server_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - EWM-STAT_URL=http://stats-server:9090/hit

  ewm-stat:
    build: ewm-stat
    container_name: ewm-stat
    depends_on:
      - stat-db
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stat_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

  stat-db:
    image: postgres:14-alpine
    container_name: db-ewm-stat
    ports:
      - "5466:5432"
    environment:
      - POSTGRES_DB=ewm_stat_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    container_name: db-ewm-main
    ports:
      - "5455:5432"
    environment:
      - POSTGRES_DB=ewm_server_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
