server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm_stat_db
    username: postgres
    password: root

---
spring:
  config:
    activate:
      on-profile: ci, test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm_stat_db
    username: test
    password: test