CREATE TABLE IF NOT EXISTS users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name  VARCHAR(50)                             NOT NULL,
    user_email VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT uq_email UNIQUE (user_email)
);

CREATE TABLE IF NOT EXISTS categories
(
    category_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name  VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (category_id),
    CONSTRAINT uq_name UNIQUE (category_name)
    );